### ISSUE TITLE
"Loading..." label flickers at page load. Does this need a style?

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#152]
Sorry - accidentally deleted this comment.

**Comment by gpxl-dev** [comment]
Yes, this needs a style. 

The loading component appears because `react-i18n` is dynamically loading translation files. It's using [suspense](https://reactjs.org/docs/concurrent-mode-suspense.html) fallbacks so we can theoretically put this further down the component tree so that anything that doens't require translation (E.g. widget frame) can be displayed with a spinner inside or something similar.

I expect that there is also an option to load the translations for a default language - we should look into this too

**Comment by piersss** [comment]
Maybe replace all text with placeholders lines when loading?

**Comment by piersss** [comment]
It would end up looking like this:

![Screenshot 2021-08-21 at 10 38 30](https://user-images.githubusercontent.com/86911296/130316178-3c4fa7b9-3505-47d9-abe4-49ce8e5776cc.png)
