### ISSUE TITLE
Search engine optimization

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#185]
- [ ] Add noindex for static, locales, etc.
- [ ] Work on sitemap / figure out URLs
- [ ] Review attached report

**Comment by dmosites** [comment]
[Full_Site_Audit_Report-Airswap_V2-27th_Aug_2021.pdf](https://github.com/airswap/airswap-web/files/7070539/Full_Site_Audit_Report-Airswap_V2-27th_Aug_2021.pdf)

**Comment by dmosites** [comment]
Fresh report:
[Full_Site_Audit_Report-airswap_site-25th_Jan_2022.pdf](https://github.com/airswap/airswap-web/files/7942229/Full_Site_Audit_Report-airswap_site-25th_Jan_2022.pdf)

**Comment by piersss** [comment]
**1 page doesn't have enough text within the title tags**

Right now the title is just "AirSwap". We should make it more descriptive, like:
- 1inch - DeFi / DEX aggregator on Ethereum, Binance Smart Chain, Optimism, Polygon, Arbitrum
- Uniswap Interface
- Polygon Web Wallet v2

**1 page doesn't have an h1 heading**
"Swap" should get the h1 heading I think.

**1 page has low text-HTML ratio**
**1 page has a low word count**
We do actually have a lot of text, but it's mostly hidden when you land on the page. We have 3 pages: Join, Protocol Fees and Gas Free Swaps. We could make them accessible by url and add to sitemap, for example:

_https://www.airswap.io/join_

This will open the app with the join modal open. But we also have the token addresses in the url so we could als have this combination:

_https://www.airswap.io/join_/0x0000000000000000000000000000000000000000/0x27054b13b1b798b345b591a4d22e6562d47ea75a_

I'm not sure this would fix the low text-HTML ratio problem but we need this anyway.

**Pages with only one internal link**
There's at lease one link to linking back to homepage on https://about.airswap.io/. But I don't think that gets crawled because it's not in the sitemap.

**No HSTS support**
This is hosting related, not sure how to fix this.

**Conclusion:**
Let's make two seperate tickets:

1. Ticket for changing site title and adding <h1> tag to "Swap".
2. Everything regarding sitemap and site routing. Discuss if we want landing pages for /join /protocol-fees and /gas-free swaps.
