### ISSUE TITLE
Listen to swap events instead of tracking transactions

### ISSUE THREAD

**Issue by gpxl-dev** [airswap/airswap-web#214]
Currently (100% RFQ interface), when an order is submitted, we listen to the transaction being successful or being reverted. 

For Last Look, the front end won't have access to the transaction (as the maker will submit the transaction).

Instead, we should listen for swap events with the same nonce, and race it against the expiry.

This will consolidate the logic regardless of the protocol used.

**Comment by gpxl-dev** [comment]
Relevant sections in code to look at (there may be others)!

After taking an order:
https://github.com/airswap/airswap-web/blob/9b9fae360bb97c02d7f6fd73afae70b11fa2adc5/src/features/orders/ordersSlice.ts#L106

After loading the page if there were pending transactions when the user left previously:
https://github.com/airswap/airswap-web/blob/9b9fae360bb97c02d7f6fd73afae70b11fa2adc5/src/features/transactions/Transactions.tsx#L37

**Comment by robbestad** [comment]
I'd be happy to work on it, though I'm sure it would have be synced up with work being done on the Last Look. Am I right in assuming that instead of polling for a transactionreceipt you would want to listen an even that would either return an RFQ swap receipt or a Last Look receipt? Or would you keep the polling and run the event listener on the nonce and resolve whichever returns first?
 
In any case, I would start by setting up a tests for the transaction so that RFQ is tested, and then expand it by adding skeleton tests for Last Look.

**Comment by gpxl-dev** [comment]
@robbestad awesome - feel free to assign yourself.

The way I am thinking about it, I don't think it is dependent on last look. Both RFQ and last look are successful when a swap event with the nonce and correct counterparties is emitted, and both have an expiry that we can use to indicate failure.

This will probably be merged before last look, so the last look branch can pull in the changes before it's completed.
