### ISSUE TITLE
Refreshing after connecting to wallet with an unsupported network disconnects the wallet

### ISSUE THREAD

**Issue by robbestad** [airswap/airswap-web#319]
* disconnect wallet
* change network to unsupported one
* connect wallet
* refresh page without switching network
-> disconnected state 

https://user-images.githubusercontent.com/1560743/140502541-3535150e-127d-4cd9-99df-869bebf03217.mp4

**Comment by gpxl-dev** [comment]
How much do we care about this issue?

It's quite niche and has a low impact to the user - to reiterate, they need to have never connected before, click "connect", ignore the "Switch network" button, and refresh the page.

If they do this, the impact will be that they have to click connect wallet again, despite having clicked it before the refresh.

Pushing back on this because we're currently using `useWeb3React` to get the connected account. In the event that the user connects to an unsupported chain, it sets `error` and does _not_ populate the account. As such fixing this is non-trivial and I think the complexity it will add to the codebase is not worth the impact of the bug.

Propose we close this issue without a fix.

For reference:

- Wallet address persisting done by `saveLastAccount` at `Wallet.tsx:202`.
- This isn't hit if `account` isn't truthy, which it isn't when `error` is. `useWeb3React` treats an invalid chain as an error.

You can verify by logging what's provided by `useWeb3React` when connected to an unsupported network:

```
account: undefined
active: false
c1: InjectedConnector {_events: {…}, _eventsCount: 3, _maxListeners: undefined, supportedChainIds: Array(9), handleNetworkChanged: ƒ, …}
chainId: undefined
error: UnsupportedChainIdError: Unsupported chain id: 42161. Supported chain ids are: 1,4,5,56,97,137,43113,43114,80001. at http://localhost:3000/static/js/vendors~main.chunk.js:39034:17
library: undefined
```
