### ISSUE TITLE
Fetch historical events

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#417]
Fetch historical EVM logs on app load to pick up Swap events that occurred between sessions

**Comment by dmosites** [comment]
Current subscription logic in `swapEventSubscriber` https://github.com/airswap/airswap-web/blob/develop/src/features/transactions/swapEventSubscriber.ts#L120

Would also want to use ethers `getLogs` to fetch Swap events that have happened since the previous app session. 
https://docs.ethers.io/v5/api/providers/provider/#Provider-getLogs
https://docs.ethers.io/v5/api/providers/types/#providers-EventFilter

**Comment by Phasor** [comment]
I have spent some time looking into this. I can only see the historic/pending transactions in the transactions tab being updated as a result of transactions (ignoring the toast popups). 

So looking at historical successful transactions, when you say we want to look at the eth logs with ethers to see if Redux has missed anything (due to a refresh for example), do you mean we should first check redux for all transactions, and then where this is say less than 10 (I think the UI will max out after that) then fetch the additional historic transactions up to 10 from the chain using ethers?

So we will always have say 10 historic transactions (unless they have done less than 10 swaps with us).

**Comment by dmosites** [comment]
On first time load, fetch all `Swap` events since block 0 where the currently connected wallet is either the `senderWallet` or `signerWallet` and record the current block number N in local storage. On a subsequent load, we fetch all `Swap` events (same filter) since block N. I don't think we need to introduce any limits on the UI at this stage.
