### ISSUE TITLE
Show MetaMask errors to user

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#503]
Right now errors from MetaMask are only shown in console and a "Error submitting swap" toast. We should better inform the user what error is exactly occurring. Here's a list of possible errors:

https://github.com/MetaMask/eth-rpc-errors/blob/main/src/error-constants.ts

Questions for Don:

1. Should a MetaMask error appear in a toaster or in the Error overlay component?
2. Should translations be added for each error?
3. Only fix the most common "User rejected transaction" error. (quick fix)

**Comment by dmosites** [comment]
Good topic. Does the app receive `rpc` or `provider` errors? Both?

1. Since it relates to the current order, error overlay with ability to dismiss and try again.
2. We could add translation keys for each but just fall back to English for now.
3. IMO rejections should just be ignored by the app and its state remain unchanged.

**Comment by piersss** [comment]
Both. Provider errors are translated and placed in the error overlay component. Rpc errors all show as a general error toaster.

To summarise: rejection should be unchanged and still show a toaster, but all other rpc errors should be shown in the error list.
