### ISSUE TITLE
Update the way the store catches and throws provider errors

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#509]
This didn't work anymore. Because the error gets "rethrown" the `code` gets moved into the `stack`. So now we have to get error from the `message`.

_Originally posted by @piersss in https://github.com/airswap/airswap-web/pull/505#discussion_r835950286_

**Comment by piersss** [comment]
In SwapWidget line 617 there's a `catch` where errors get processed. These errors are thrown from ordersSlice. The problem is that ordersSlice receives an error from MetaMask and then throws it again.

Solution: get the error from the store, the last error already gets stored in ordersSlice as `error`. But then you'll have to rewrite a bunch of code in SwapWidget which will could introduce other bugs.

I will try to fix it this week, but anyone is welcome to try.

**Comment by piersss** [comment]
I think I have a solution, we should rewrite all the `try...catch` clauses in ordersSlice to `Promise resolve reject` clauses. That would make the code a lot cleaner.

**Comment by piersss** [comment]
Ok forget the last comment. The problem was that `takeBestOption` had too much logic and all ended up in the same `try...catch`, so you had all the different errors all ending up there, which made it hard to debug.  I fixed it by splitting `takeBestOption` into two separate functions: `swapWithRequestForQuote` and `swapWithLastLook` with their own `try...catch` clauses so the errors can be acted on accordingly.

At a later point I would like some of the logic `swapWithRequestForQuote` and `swapWithLastLook` out of the SwapWidget component and into the `features/orders` store functions because there's too much logic going on in the component.

**Comment by dmosites** [comment]
Included in #527
