### ISSUE TITLE
Design for error messages

### ISSUE THREAD

**Issue by gregplumbly** [airswap/airswap-web#68]
e.g no quotes returned

**Comment by NassK44** [comment]
Is there a list/Overview of the error messages/Types we need?

**Comment by gregplumbly** [comment]
Not currently, but situations like 'There was no quote returned'.

I think the big question is if they appear in a popover like #69 or somewhere within the swap widget frame.

**Comment by gregplumbly** [comment]
Example from Zapper
<img width="301" alt="Screenshot 2021-07-01 at 18 55 44" src="https://user-images.githubusercontent.com/4796/124256014-549add00-db1a-11eb-8836-66ac9cb3d637.png">

**Comment by gpxl-dev** [comment]
> I think the big question is if they appear in a popover like #69 or somewhere within the swap widget frame.

Yes, this!

We can obviously work out what the wording for each is later, but we should have some designs / flows for what happens when things don't work properly. 

One (unlikely?) example: Approval fails:

1. User enters sender token and amount and requests a quote
2. Quote appears
3. User has to approve -> button goes to loading state during approval, then the approval fails

Currently the UI just shows the past transaction failing, but we obviously need to notify the user that it failed and that they'll need to try again - where does this fit into the UI?

Other errors:
- No orders (aka quotes) for pair
- Order expires
- Bad input state (e.g.) "Insufficient balance"
- Order failed - this one is more complex than approval as you can't simply try again (unless within expiry)
