### ISSUE TITLE
Narrow the "My Swaps" screen to regular widget width

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#695]
Judging by the data we now have on screen it may be possible for this screen to be the standard widget width, which would be much smoother from a UX standpoint.

![Image](https://user-images.githubusercontent.com/1601469/206545398-53f2454f-5b4d-47d6-aa67-c9768b3656d6.png)

**Comment by 2xAST** [comment]
[Proposal for a condensed version](https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/airswap-web?node-id=13418%3A17396&t=h04cUYyDbswdoYwt-4)

**Comment by dmosites** [comment]
Looks like it fits! Do we need the "pair" column? It adds color but not sure how informative it is against the attention it takes. Perhaps we could pull the "status" column over from the original (green dots for live or not-live).

Expiry column could be "Status" and include possible values e.g. "1D 23H", "EXPIRED", "TAKEN", "CANCELLED".

Thoughts?

**Comment by 2xAST** [comment]
[Here ](https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/airswap-web?node-id=13428%3A16926&t=ULBjYpACxDzvMjsI-4) is a version with the dots instead of the pair, both versions are fine imo.  As both, the pair and the dots are redundant information and only serve a visual purpose to understand the data faster.

The one benefit the dots have is they are more space saving.

Changing the Name label of Expiry to Status makes sense, because we now include not only a timestamp.

**Comment by dmosites** [comment]
Version with dots looks good to me. While it's very "frugal" it gets the job done.
